CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE,
  name VARCHAR(50) NOT NULL,
  last_name VARCHAR(100),
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(15),
  user_type TEXT CHECK (user_type IN ('customer','admin')),
  balance NUMERIC(8,2) DEFAULT 0,
  status TEXT CHECK (status IN ('verified','non-verified','suspended')) DEFAULT 'non-verified',
  driver_license VARCHAR(100),
  created_at TIMESTAMP,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE vehicle_types (
  type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  description TEXT,
  range_km INT,
  max_speed INT,
  adapted_reduced_mobility BOOLEAN DEFAULT false,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE vehicles (
  vehicle_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_plate VARCHAR(10) UNIQUE,
  model VARCHAR(50),
  vehicle_type_id INT,
  battery_level INT,
  current_range INT,
  total_km NUMERIC(8,2) DEFAULT 0,
  status TEXT CHECK (status IN ('available','reserved','in_use','out_of_service')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE reservations (
  reservation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  vehicle_id INT,
  reservation_datetime TIMESTAMP,
  deadline_datetime TIMESTAMP,
  reservation_status TEXT CHECK (reservation_status IN ('pending','confirmed','cancelled','expired')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE trips (
  trip_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  vehicle_id INT,
  start_latitude NUMERIC(10,8),
  start_longitude NUMERIC(11,8),
  end_latitude NUMERIC(10,8),
  end_longitude NUMERIC(11,8),
  start_datetime TIMESTAMP,
  end_datetime TIMESTAMP,
  trip_status TEXT CHECK (trip_status IN ('in_progress','finished','cancelled')),
  payment_type TEXT CHECK (payment_type IN ('balance','single_ticket')),
  total_price NUMERIC(8,2),
  traveled_km NUMERIC(5,2) DEFAULT 0,
  time_used INT,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE balance_movements (
  movement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  type TEXT CHECK (type IN ('recharge','consumption','refund')),
  amount NUMERIC(8,2),
  movement_datetime TIMESTAMP,
  description VARCHAR(255),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE single_tickets (
  ticket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  trip_id INT,
  amount NUMERIC(8,2),
  purchase_date TIMESTAMP,
  status TEXT CHECK (status IN ('pending','paid','cancelled')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE maintenance (
  maintenance_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id INT,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  type TEXT CHECK (type IN ('inspection','repair','cleaning','update')),
  description TEXT,
  status TEXT CHECK (status IN ('pending','in_progress','completed')),
  cost NUMERIC(8,2) DEFAULT 0,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE locations (
  location_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id INT,
  latitude NUMERIC(10,8),
  longitude NUMERIC(11,8),
  datetime TIMESTAMP,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE alerts (
  alert_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id INT,
  user_id INT,
  type TEXT CHECK (type IN ('technical','security','payment','fraud')),
  description TEXT,
  alert_date TIMESTAMP,
  status TEXT CHECK (status IN ('open','in_process','closed')),
  priority TEXT CHECK (priority IN ('low','medium','high','critical')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE geofencing_config (
  zone_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_name VARCHAR(100),
  center_latitude NUMERIC(10,8),
  center_longitude NUMERIC(11,8),
  radius_meters INT,
  max_speed_allowed INT,
  type TEXT CHECK (type IN ('school','hospital','historic_center','residential_area')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE user_logs (
  log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  action TEXT CHECK (action IN ('reservation','cancellation','trip_start','trip_end','login','logout')),
  datetime TIMESTAMP,
  extra_data TEXT,
  deleted BOOLEAN DEFAULT false
);

-- Foreign keys
ALTER TABLE vehicles ADD FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_types (type_id);

ALTER TABLE reservations ADD FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE reservations ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);

ALTER TABLE trips ADD FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE trips ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);

ALTER TABLE maintenance ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);
ALTER TABLE locations ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);

ALTER TABLE balance_movements ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE single_tickets ADD FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE single_tickets ADD FOREIGN KEY (trip_id) REFERENCES trips (trip_id);

ALTER TABLE alerts ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);
ALTER TABLE alerts ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_logs ADD FOREIGN KEY (user_id) REFERENCES users (user_id);


 
-- Sample data inserts
-- Users
INSERT INTO users (user_id, username, name, last_name, email, password, phone, user_type, balance, status, driver_license, created_at, deleted) VALUES
(1, 'admin', 'Admin', 'User', 'admin@example.com', 'adminpass', '0000000000', 'admin', 1000.00, 'verified', '', NOW(), false),
(2, 'jdoe', 'John', 'Doe', 'john.doe@example.com', 'password', '111222333', 'customer', 25.50, 'verified', 'DL123456', NOW(), false),
(3, 'jane', 'Jane', 'Smith', 'jane.smith@example.com', 'password', '222333444', 'customer', 0.00, 'non-verified', 'DL654321', NOW(), false),
(4, 'bob', 'Bob', 'Brown', 'demo@test.com', 'Passw0rd_', '333444555', 'admin', 10000.00, 'verified', 'DL999999', NOW(), false);
-- Vehicle types
INSERT INTO vehicle_types (type_id, name, description, range_km, max_speed, adapted_reduced_mobility, deleted) VALUES
(1, 'E-Scooter', 'Light electric scooter', 20, 25, false, false),
(2, 'E-Bike', 'Pedal-assisted electric bike', 60, 30, false, false),
(3, 'Electric Car', 'Small electric car', 200, 120, true, false);

-- Vehicles
INSERT INTO vehicles (vehicle_id, license_plate, model, vehicle_type_id, battery_level, current_range, total_km, status, deleted) VALUES
(1, 'SC-1001', 'Xiaomi M365', 1, 85, 17, 123.45, 'available', false),
(2, 'BK-2002', 'RadRunner 1', 2, 60, 36, 560.00, 'available', false),
(3, 'EC-3003', 'CityEV', 3, 95, 190, 10234.50, 'in_use', false);

-- Reservations
INSERT INTO reservations (reservation_id, user_id, vehicle_id, reservation_datetime, deadline_datetime, reservation_status, deleted) VALUES
(1, 2, 1, NOW(), NOW() + INTERVAL '30 minutes', 'confirmed', false);

-- Trips
INSERT INTO trips (trip_id, user_id, vehicle_id, start_latitude, start_longitude, end_latitude, end_longitude, start_datetime, end_datetime, trip_status, payment_type, total_price, traveled_km, time_used, deleted) VALUES
(1, 2, 1, 41.38510000, 2.17340000, 41.39000000, 2.17000000, NOW() - INTERVAL '20 minutes', NOW(), 'finished', 'balance', 3.50, 1.20, 15, false);

-- Balance movements
INSERT INTO balance_movements (movement_id, user_id, type, amount, movement_datetime, description, deleted) VALUES
(1, 2, 'recharge', 50.00, NOW() - INTERVAL '1 day', 'Initial top-up', false),
(2, 2, 'consumption', 3.50, NOW(), 'Trip payment', false);

-- Single tickets
INSERT INTO single_tickets (ticket_id, user_id, trip_id, amount, purchase_date, status, deleted) VALUES
(1, 3, NULL, 2.50, NOW(), 'pending', false);

-- Maintenance
INSERT INTO maintenance (maintenance_id, vehicle_id, start_date, end_date, type, description, status, cost, deleted) VALUES
(1, 3, NOW() - INTERVAL '7 days', NOW() - INTERVAL '6 days', 'inspection', 'Routine inspection', 'completed', 0.00, false);

-- Locations
INSERT INTO locations (location_id, vehicle_id, latitude, longitude, datetime, deleted) VALUES
(1, 1, 41.38510000, 2.17340000, NOW() - INTERVAL '10 minutes', false);

-- Alerts
INSERT INTO alerts (alert_id, vehicle_id, user_id, type, description, alert_date, status, priority, deleted) VALUES
(1, 3, NULL, 'technical', 'Low tire pressure', NOW() - INTERVAL '5 days', 'open', 'medium', false);

-- Geofencing configuration
INSERT INTO geofencing_config (zone_id, zone_name, center_latitude, center_longitude, radius_meters, max_speed_allowed, type, deleted) VALUES
(1, 'City Center', 41.38510000, 2.17340000, 500, 20, 'historic_center', false);

-- User logs
INSERT INTO user_logs (log_id, user_id, action, datetime, extra_data, deleted) VALUES
(1, 2, 'login', NOW() - INTERVAL '1 hour', NULL, false),
(2, 2, 'reservation', NOW() - INTERVAL '30 minutes', 'reservation_id=1', false);


