CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(50) NOT NULL,
  last_name VARCHAR(100),
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(15),
  user_type TEXT CHECK (user_type IN ('customer','admin')),
  balance NUMERIC(8,2) DEFAULT 0,
  status TEXT CHECK (status IN ('verified','non-verified','suspended')) DEFAULT 'non-verified',
  driver_license VARCHAR(100),
  created_at TIMESTAMP,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE vehicle_types (
  type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  description TEXT,
  range_km INT,
  max_speed INT,
  adapted_reduced_mobility BOOLEAN DEFAULT false,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE vehicles (
  vehicle_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_plate VARCHAR(10) UNIQUE,
  model VARCHAR(50),
  vehicle_type_id INT,
  battery_level INT,
  current_range INT,
  total_km NUMERIC(8,2) DEFAULT 0,
  status TEXT CHECK (status IN ('available','reserved','in_use','out_of_service')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE reservations (
  reservation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  vehicle_id INT,
  reservation_datetime TIMESTAMP,
  deadline_datetime TIMESTAMP,
  reservation_status TEXT CHECK (reservation_status IN ('pending','confirmed','cancelled','expired')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE trips (
  trip_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  vehicle_id INT,
  start_latitude NUMERIC(10,8),
  start_longitude NUMERIC(11,8),
  end_latitude NUMERIC(10,8),
  end_longitude NUMERIC(11,8),
  start_datetime TIMESTAMP,
  end_datetime TIMESTAMP,
  trip_status TEXT CHECK (trip_status IN ('in_progress','finished','cancelled')),
  payment_type TEXT CHECK (payment_type IN ('balance','single_ticket')),
  total_price NUMERIC(8,2),
  traveled_km NUMERIC(5,2) DEFAULT 0,
  time_used INT,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE balance_movements (
  movement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  type TEXT CHECK (type IN ('recharge','consumption','refund')),
  amount NUMERIC(8,2),
  movement_datetime TIMESTAMP,
  description VARCHAR(255),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE single_tickets (
  ticket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  trip_id INT,
  amount NUMERIC(8,2),
  purchase_date TIMESTAMP,
  status TEXT CHECK (status IN ('pending','paid','cancelled')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE maintenance (
  maintenance_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id INT,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  type TEXT CHECK (type IN ('inspection','repair','cleaning','update')),
  description TEXT,
  status TEXT CHECK (status IN ('pending','in_progress','completed')),
  cost NUMERIC(8,2) DEFAULT 0,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE locations (
  location_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id INT,
  latitude NUMERIC(10,8),
  longitude NUMERIC(11,8),
  datetime TIMESTAMP,
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE alerts (
  alert_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id INT,
  user_id INT,
  type TEXT CHECK (type IN ('technical','security','payment','fraud')),
  description TEXT,
  alert_date TIMESTAMP,
  status TEXT CHECK (status IN ('open','in_process','closed')),
  priority TEXT CHECK (priority IN ('low','medium','high','critical')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE geofencing_config (
  zone_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_name VARCHAR(100),
  center_latitude NUMERIC(10,8),
  center_longitude NUMERIC(11,8),
  radius_meters INT,
  max_speed_allowed INT,
  type TEXT CHECK (type IN ('school','hospital','historic_center','residential_area')),
  deleted BOOLEAN DEFAULT false
);

CREATE TABLE user_logs (
  log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  action TEXT CHECK (action IN ('reservation','cancellation','trip_start','trip_end','login','logout')),
  datetime TIMESTAMP,
  extra_data TEXT,
  deleted BOOLEAN DEFAULT false
);

-- Foreign keys
ALTER TABLE vehicles ADD FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_types (type_id);
ALTER TABLE vehicles ADD FOREIGN KEY (owner_id) REFERENCES users (user_id);

ALTER TABLE reservations ADD FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE reservations ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);

ALTER TABLE trips ADD FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE trips ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);

ALTER TABLE maintenance ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);
ALTER TABLE locations ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);

ALTER TABLE balance_movements ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE single_tickets ADD FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE single_tickets ADD FOREIGN KEY (trip_id) REFERENCES trips (trip_id);

ALTER TABLE alerts ADD FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id);
ALTER TABLE alerts ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_logs ADD FOREIGN KEY (user_id) REFERENCES users (user_id);


