
CREATE TABLE "Usuaris" (
  "id_usuari" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar(50),
  "cognoms" varchar(100),
  "email" varchar(100) UNIQUE,
  "contrasenya" varchar(255),
  "telefon" varchar(15),
  "data_registre" datetime,
  "tipus_usuari" enum(client,endclient),
  "saldo" decimal(8,2) DEFAULT 0,
  "estat" enum(actiu,inactiu,suspes) DEFAULT 'actiu',
  "actiu" boolean DEFAULT 'false',
  "permiso_conducir" varchar(100),
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "TipusVehicle" (
  "id_tipus" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" varchar(100),
  "descripcio" text,
  "autonomia_km" int,
  "velocitat_max" int,
  "adaptat_mobilitat_reduida" boolean DEFAULT false,
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "Vehicles" (
  "id_vehicle" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "matricula" varchar(10) UNIQUE,
  "model" varchar(50),
  "id_tipus_vehicle" int,
  "id_propietari" int,
  "nivell_bateria" int,
  "autonomia_actual" int,
  "km_totals" decimal(8,2) DEFAULT 0,
  "estat" enum(disponible,reservat,en_ús,manteniment,fora_servei),
  "qr_code" varchar(100) UNIQUE,
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "Reserves" (
  "id_reserva" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuari" int,
  "id_vehicle" int,
  "data_hora_reserva" datetime,
  "data_hora_limite" datetime,
  "estat_reserva" enum(pendent,confirmada,cancel·lada,expirada),
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "Viajes" (
  "id_viaje" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuari" int,
  "id_vehicle" int,
  "latitud_inici" decimal(10,8),
  "longitud_inici" decimal(11,8),
  "latitud_fi" decimal(10,8),
  "longitud_fi" decimal(11,8),
  "data_hora_inici" datetime,
  "data_hora_fi" datetime,
  "estat_viaje" enum(en_curs,finalitzada,cancel·lada),
  "tipus_pagament" enum(saldo,bitllet_individual),
  "preu_total" decimal(8,2),
  "km_recorreguts" decimal(5,2) DEFAULT 0,
  "temps_utilitzat" int,
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "MovimentsSaldo" (
  "id_moviment" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuari" int,
  "tipus" enum(recarrega,consum,reembors),
  "import" decimal(8,2),
  "data_moviment" datetime,
  "descripcio" varchar(255),
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "BitlletsIndividuals" (
  "id_bitllet" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuari" int,
  "id_viaje" int,
  "import" decimal(8,2),
  "data_compra" datetime,
  "estat" enum(pendent,pagat,cancel·lat),
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "Manteniments" (
  "id_manteniment" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_vehicle" int,
  "data_inici" datetime,
  "data_fi" datetime,
  "tipus" enum(revisió,reparació,neteja,actualització),
  "descripcio" text,
  "estat" enum(pendent,en_curs,finalitzat),
  "cost" decimal(8,2) DEFAULT 0,
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "Ubicacions" (
  "id_ubicacio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_vehicle" int,
  "latitud" decimal(10,8),
  "longitud" decimal(11,8),
  "data_hora" datetime,
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "Alertes" (
  "id_alerta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_vehicle" int,
  "id_usuari" int,
  "tipus" enum(tecnica,seguretat,pagament,frau),
  "descripcio" text,
  "data_alerta" datetime,
  "estat" enum(oberta,en_proces,tancada),
  "prioritat" enum(baixa,mitjana,alta,critica),
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "ConfiguracioGeofencing" (
  "id_zona" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_zona" varchar(100),
  "latitud_centre" decimal(10,8),
  "longitud_centre" decimal(11,8),
  "radi_metres" int,
  "velocitat_maxima_permesa" int,
  "tipus" enum(escola,hospital,centre_historic,zona_residencial),
  "deleted" boolean DEFAULT 'false'
);

CREATE TABLE "LogsUs" (
  "id_log" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuari" int,
  "accio" enum(reserva,cancel·lacio,inici_viatge,fi_viatge,login,logout),
  "data_hora" datetime,
  "dades_extra" text,
  "deleted" boolean DEFAULT 'false'
);

ALTER TABLE "Vehicles" ADD FOREIGN KEY ("id_tipus_vehicle") REFERENCES "TipusVehicle" ("id_tipus");

ALTER TABLE "Vehicles" ADD FOREIGN KEY ("id_propietari") REFERENCES "Usuaris" ("id_usuari");

ALTER TABLE "Reserves" ADD FOREIGN KEY ("id_usuari") REFERENCES "Usuaris" ("id_usuari");

ALTER TABLE "Reserves" ADD FOREIGN KEY ("id_vehicle") REFERENCES "Vehicles" ("id_vehicle");

ALTER TABLE "Viajes" ADD FOREIGN KEY ("id_usuari") REFERENCES "Usuaris" ("id_usuari");

ALTER TABLE "Viajes" ADD FOREIGN KEY ("id_vehicle") REFERENCES "Vehicles" ("id_vehicle");

ALTER TABLE "Manteniments" ADD FOREIGN KEY ("id_vehicle") REFERENCES "Vehicles" ("id_vehicle");

ALTER TABLE "Ubicacions" ADD FOREIGN KEY ("id_vehicle") REFERENCES "Vehicles" ("id_vehicle");

ALTER TABLE "MovimentsSaldo" ADD FOREIGN KEY ("id_usuari") REFERENCES "Usuaris" ("id_usuari");

ALTER TABLE "BitlletsIndividuals" ADD FOREIGN KEY ("id_usuari") REFERENCES "Usuaris" ("id_usuari");

ALTER TABLE "BitlletsIndividuals" ADD FOREIGN KEY ("id_viaje") REFERENCES "Viajes" ("id_viaje");

ALTER TABLE "Alertes" ADD FOREIGN KEY ("id_vehicle") REFERENCES "Vehicles" ("id_vehicle");

ALTER TABLE "Alertes" ADD FOREIGN KEY ("id_usuari") REFERENCES "Usuaris" ("id_usuari");

ALTER TABLE "LogsUs" ADD FOREIGN KEY ("id_usuari") REFERENCES "Usuaris" ("id_usuari");


